config/routes.rb
Rails.application.routes.draw do
  root 'members#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members
  resources :matches, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/header.rb
class Header < ApplicationRecord
  belongs_to :member

  enum heading_type: [:h1, :h2, :h3]

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :member
  belongs_to :matched_member, class_name: "Member"

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse? 

  def create_inverse
    self.class.create(inverse_match_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_match_options)
  end

  def inverses
    self.class.where(inverse_match_options)
  end

  def inverse_match_options
    { matched_member_id: member_id, member_id: matched_member_id }
  end

end

app/models/member.rb
class Member < ApplicationRecord
  searchkick

  has_many :matches
  has_many :matched_members, through: :matches, dependent: :destroy
  has_many :headers

  before_save :set_short_url, if: :original_url_changed?
  after_create :scrape_headings

  validates :name, :original_url, presence: true
  validates :original_url, url: true

  def search_data
    { name: name }
  end

  def set_short_url
    self.short_url = Bitly.client.shorten(original_url).short_url
  end

  def scrape_headings
    HeadingScraper.new.scrape(id, original_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match.member, notice: "Successfully added #{@match.matched_member.name} as friend." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    respond_to do |format|
      format.html { redirect_to member_path(@match.member_id), notice: "Removed #{@match.matched_member.name} as friend." }
      format.json { head :no_content }
    end
  end

  private

    def match_params
      params.require(:match).permit(:member_id, :matched_member_id)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    query = params[:q].presence || "*"
    @members = Member.search(query, where: {id: {not: @member.id}})
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :original_url, :short_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndOpen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :original_url %>
    <%= form.text_field :original_url, id: :member_original_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short url</th>
      <th>Headings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, member %></td>
        <td><%= link_to member.short_url, member.short_url, target: '_blank' %></td>
        <td><%= member.headers.count %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Original url:</strong>
  <%= link_to @member.original_url, @member.original_url, target: '_blank' %>
</p>

<p>
  <strong>Headings:</strong>
</p>
<% @member.headers.each do |header| %>
  <p>
    <strong><%= header.heading_type %></strong>
    <%= header.detail %>
  </p>
<% end %>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back to home', members_path %>

<div style="margin:20px 0px;">
<%= form_tag member_path(@member), method: :get do %>
  <%= text_field_tag :q, nil, placeholder: "Search" %>
  <%= submit_tag 'Search', name: nil %>
  <% if (params[:q]).present? %>
    <%= link_to 'Clear Search', member_path(@member) %>
  <% end %>
<% end %>
</div> 


<h3><%= (params[:q]).present? ? 'Search Results' : 'Selected Friends' %></h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short url</th>
      <th colspan="3">Friends?</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, member %></td>
        <td><%= link_to member.short_url, member.short_url, target: '_blank' %></td>
        <td> 
          <% if @member.matched_members.include?(member) %>
            <%= link_to 'Remove from friends', match_path(@member.matches.find_by(matched_member_id: member.id)), method: :delete, data: { confirm: 'Are you sure?' }%>
          <% else %>
            <%= link_to 'Add as Friend', matches_path(match: { matched_member_id: member, member_id: @member.id}), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>